### PR TITLE
More user friendly error messages

### LINKED ISSUE #439: More user-friendly messages in error responses
ie.  `{ error: “Incorrect login/email or password” }` instead of `{ error: "user" }` or `{ error: "password"}` in login failed response

### PR DESCRIPTION
**Pull request by wojciechUrbanski**
Fixes #439 

More user friendly error messages

### CODE REVIEW

File: backend/src/main/scala/com/softwaremill/bootzooka/user/UserService.scala [hunk 1]
```diff
@@ -100,23 +100,23 @@ class UserService(
...
+      _ <- verifyPassword(user, currentPassword, validationErrorMsg = "Incorrect current password")
       _ = logger.debug(s"Changing password for user: $userId")
       _ <- userModel.updatePassword(userId, User.hashPassword(newPassword))
     } yield ()
 
   private def userOrNotFound(op: ConnectionIO[Option[User]]): ConnectionIO[User] = {
     op.flatMap {
       case Some(user) => user.pure[ConnectionIO]
-      case None       => Fail.NotFound("user").raiseError[ConnectionIO, User]
+      case None       => Fail.Unauthorized("Incorrect login/email or password").raiseError[ConnectionIO, User]
```
Comment (adamw) [inline backend/src/main/scala/com/softwaremill/bootzooka/user/UserService.scala:111]: We should probably extract this message to a constant so that it's not repeated, and the fact that the constant is used twice will also be informative for the developer

File: backend/src/main/scala/com/softwaremill/bootzooka/passwordreset/PasswordResetService.scala [hunk 2]
```diff
@@ -27,7 +27,7 @@ class PasswordResetService(
 
   def forgotPassword(loginOrEmail: String): ConnectionIO[Unit] = {
     userModel.findByLoginOrEmail(loginOrEmail.lowerCased).flatMap {
-      case None => Fail.NotFound("user").raiseError[ConnectionIO, Unit]
+      case None => ().pure[ConnectionIO]
```
Comment (adamw) [inline backend/src/main/scala/com/softwaremill/bootzooka/passwordreset/PasswordResetService.scala:30]: maybe add a debug-log so that it's visible in the logs that the user hasn't been found? (as it's not visible in the UI)

**Review by adamw — APPROVED** [review]
